[[watch]]
path = "~/pad/notes/"

[[watch]]
path = "~/pad/songs/"

[[watch]]
path = "~/pad/art-of-non-machine-translation-skill"

[[watch]]
path = "~/projects/home/sonauto-gui"

[[watch]]
path = "~/projects/home/deer-diary"

[[watch]]
path = "~/projects/home/garlandano"

[[watch]]
path = "~/projects/home/design-tocs"
