#let due(year, month, day) = metadata(("mindtape.due", datetime(year: year, month: month, day: day)))
#let start(year, month, day) = metadata(("mindtape.start", datetime(year: year, month: month, day: day)))
#let id(uuid) = metadata(("mindtape.id", uuid))
#let tag(name) = metadata(("mindtape.tag", name))
#let rank(n) = metadata(("mindtape.rank", n))
#let high = rank(100)
#let medium = rank(50)
#let low = rank(10)
